Fifth milestone
moinkhanif/react-calculator pull request #4
Opened 2020-12-26 07:24 UTC by moinkhanif

2020-12-26 08:55 UTC, Forison requested changes
## Status::Changes Required❌
# 🙋‍♂️ @moinkhanif 
#### You have done a good job on this milestone so far, however, there are a few changes we have to make to get the project approved🤗.
* [x] When I divide a number by zero, the application throws an error instead of returning undefined. ie `20/0` will throw an error.
* [ ] Let us improve the behavior of percentage thus
- When the percentage is selected after a number it should return the result of the number divided by 100. ie `30` then `%` should display `0.3`
- When percentage is selected at the time number1, number2 and operation are selected, the selection of percentage should return the result of the computation in percentage thus the resultant value over 100. ie `20+40` then `%` should return `0.6`
* [ ] Let us improve the behavior of `%`, it ought to mutate each of the two operand not the symbol per se. ie  `20+40` then select `%` should return `-20-40` or `-20+-40`
 - [ ] Check other comments below👇
#### That is it kindly make the changes and submit a re-review💪
#### Happy coding🙏
Addo Forison

2020-12-26 08:55 UTC, Forison commented on src/components/App/App.jsx
> +/* eslint-disable react/destructuring-assignment */
**[OPTIONAL]** 
By disabling eslint rule, you risk missing out on the object of the rule.

2020-12-26 08:55 UTC, Forison commented on src/components/App/App.jsx
> +class App extends Component {
**[OPTIONAL]** 
per the convention of container/component pattern, components with their own state ought to be in the container folder, whilst other stateless ones which depends on props in the component folder

2020-12-26 08:55 UTC, Forison commented on src/components/Button/button.component.jsx
> +  title: propTypes.string,
**[Required]**
Let us validate handleClick as well. All props have to be validated.

2020-12-26 08:55 UTC, Forison commented on src/components/ButtonPanel/button-panel.component.jsx
> +                  clickHandler={handleClick(props)}
**[Required]**
Let us validate handleClick as well. All props have to be validated.

2020-12-26 18:24 UTC, mosaaleb requested changes
#### Changes required

Well done @moinkhanif :clap:. You have handled all the requirements from the prevoius review. Good job adding the styles to your project. However, we need to finish the REAME file before finishing this project. 

Let's add more detailed instructions on how to clone, setup, run this project. Let's also update the status of the fifth milestone by adding a short summary about this milestones.
![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png)

Please handle this requirement and submit a new code review.

##### Muhammad Ebeid

2020-12-28 12:36 UTC, MuriloRoque approved these changes
## Status: Approved :green_circle: 

### Hello @moinkhanif :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-12-28 12:39 UTC, merged